# Generated by Django 3.2 on 2023-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_alter_employee_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
