# Generated by Django 3.2 on 2023-07-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_alter_employee_store'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(related_name='assigned_stores', to='employes.Employee'),
        ),
    ]
